/**
 * Projects data: the single source of truth for /projects (ProjectsSection) and
 * the project evidence on /skills. Moved out of components/sections/ProjectsSection.jsx
 * so plain Node scripts (scripts/check-career-data.mjs) can import it without JSX.
 */

export const PROJECTS = [
  {
    id: "signal",
    title: "Signal",
    subtitle: "Governance Layer for AI-Assisted Government Data",
    org: "Personal · Open Source",
    period: "Jun 2026 – Present",
    tag: "AI Governance",
    domain: ["AI / ML", "Open Source"],
    status: "Live · v1.14",
    stack: [
      "Python",
      "FastAPI",
      "LLM",
      "Modal",
      "Pydantic v2",
      "NumPy",
      "SciPy",
      "Docker",
      "GitHub Actions",
      "EU AI Act",
      "DTA v2.0",
    ],
    summary:
      "A governed data product that puts AI governance on the request path — tamper-evident hash-chained audit logs, auto-generated DTA and EU AI Act compliance artefacts, and faithfulness-checked LLM narratives. The live reference implementation analyses South Australian and NYC crime statistics with Mann-Kendall trend tests, Sen-slope forecasting, and z-score anomaly review.",
    impact:
      "Live deployment · 128 tests · Tamper-evident audit + DTA v2.0 governance set · Open-core product",
    link: "https://github.com/rNLKJA/signal",
    linkLabel: "View Signal repository on GitHub",
    demo: "https://rnlkja--signal-api-api.modal.run",
    demoLabel: "Open the live Signal dashboard",
    caseStudy: "/projects/signal",
    featured: true,
    current: true,
  },
  {
    id: "ranking-radar",
    title: "Ranking Radar",
    subtitle: "University Rankings Visualisation & Open Dataset",
    org: "Personal · Open Source",
    period: "Jun 2026",
    tag: "Data Visualisation",
    domain: ["Open Source", "Research"],
    status: "Live",
    stack: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind",
      "shadcn/ui",
      "D3.js",
      "Node.js",
      "Data Pipeline",
      "FAIR Data",
      "Vercel",
    ],
    summary:
      "Brings four ranking systems (QS, Times Higher Education, and two U.S. News rankings) together for 3,790 universities across 40 years. A no-hard-coding pipeline pulls each ranking live and recovers QS history from archived edition IDs, published as an open, FAIR-licensed dataset.",
    impact: "3,790 universities · 4 ranking systems · live-sourced FAIR open dataset",
    link: "https://qs-usnews-ranking-viz.vercel.app",
    linkText: "Visit live demo ↗",
    linkLabel: "Open Ranking Radar live demo",
  },
  {
    // Private repo and private production system holding real customer data:
    // no link or demo on purpose. The case study describes how it works only.
    id: "order-system",
    title: "Meal-Prep Studio Order System",
    subtitle: "Members, Prepaid Cards, Orders & Finance App",
    org: "Family Business · Private",
    period: "Apr 2026 – Present",
    tag: "Full Stack",
    domain: "Personal",
    status: "In production · Private",
    stack: [
      "TypeScript",
      "Expo",
      "React Native",
      "Hono",
      "Turso (libSQL)",
      "Drizzle ORM",
      "Zod",
      "argon2id + JWT",
      "Vitest",
      "Turborepo",
      "Vercel",
      "GitHub Actions",
    ],
    summary:
      "Built as sole developer for my mum's meal-prep studio: one system for members, prepaid meal cards, daily orders, kitchen and delivery, and finance. A single Expo codebase builds for iOS, Android and the web, on a Hono API on Vercel with Turso (libSQL) and Drizzle. It was built to replace group-chat sign-ups that were tallied by hand and re-keyed into an Excel workbook.",
    impact:
      "Sole developer · In production since April 2026 · One codebase for iOS, Android and web",
    caseStudy: "/projects/order-system",
    current: true,
  },
  {
    id: "sapol-epsb",
    title: "SAPOL EPSB Analytics",
    subtitle: "Professional Standards Reporting & Tooling",
    org: "South Australia Police, Ethical and Professional Standards Branch",
    period: "Mar 2026 – Present",
    tag: "Analytics",
    domain: "Government",
    status: "In production",
    stack: [
      "IAPro",
      "BlueTeam",
      "Python",
      "Power BI",
      "SQL Server",
      "FastAPI",
      "Vue",
      "Statistical modelling",
    ],
    summary:
      "As ASO7 Senior Data Analyst in the Intelligence & Probity Unit of SAPOL's Ethical and Professional Standards Branch, produces the quarterly Use of Force and Vehicle Pursuit statistical reports, led an end-to-end review of the complaint administration workflow, and analysed a financial year of expiation notices. Also built a Python client and web console for the IAPro and BlueTeam APIs, covering more than 1,100 endpoints.",
    impact:
      "Quarterly executive reporting · Admin workflow review · 1,100+ IAPro/BlueTeam endpoints in one client",
    current: true,
  },
  {
    id: "mapiva",
    title: "Mapiva",
    subtitle: "Map-First Social Discovery App",
    org: "Mapiva (Co-founded)",
    period: "Aug 2025 – Present",
    tag: "Mobile Dev",
    domain: "Startup",
    status: "Beta 2027",
    stack: ["React Native", "Expo", "Django", "Rust", "PostgreSQL", "GitHub Actions"],
    summary:
      "Co-founded a Melbourne startup building a map-first app for discovering people and events nearby. As Dev Lead, owns the technical architecture (an Expo React Native client on a Django, Rust and PostgreSQL backend, shipped through GitHub Actions) and leads code review for a part-time engineering team.",
    impact: "Co-founder · Dev Lead · Beta planned for early 2027",
    current: true,
  },
  {
    id: "sa-address",
    title: "SA Address Generator",
    subtitle: "Socio-Economic & Remoteness-Based Address Tool",
    org: "Consumer and Business Services SA",
    period: "Aug 2025",
    tag: "Data Engineering",
    domain: "Government",
    status: "Delivered",
    stack: [
      "Python",
      "Mapbox API",
      "SEIFA",
      "ABS Remoteness",
      "GeoPandas",
      "Pandas",
      "Data Validation",
      "Faker",
    ],
    summary:
      "Built an internal tool to generate validated real South Australian addresses based on socio-economic status (SEIFA indices) and remoteness classifications — filling a gap no public API could address. All outputs verified via Mapbox API.",
    impact: "Validated address generation · SEIFA + remoteness filtering · Internal QA tool",
    link: "https://github.com/rNLKJA/SA-Mock-Address-Generator",
    linkLabel: "View SA Address Generator repository on GitHub",
  },
  {
    id: "us-political",
    title: "US Political Data",
    subtitle: "Presidential Debate & Campaign Document Scraper",
    org: "Personal Research",
    period: "Aug 2025",
    tag: "Data Engineering",
    domain: ["Research", "Open Source"],
    status: "Open source",
    stack: [
      "Python",
      "Web scraping",
      "Multi-threading",
      "CSV pipeline",
      "BeautifulSoup",
      "Requests",
      "Pandas",
      "Rate limiting",
    ],
    summary:
      "Scraped the UC Santa Barbara American Presidency Project to collect ~180 presidential debate transcripts and ~25,000 campaign documents, with multi-threaded processing, rate limiting, and full metadata extraction.",
    impact: "~25,000 documents collected · Decades of US political communication data",
    link: "https://github.com/rNLKJA/Political-Data-Collection-System",
    linkLabel: "View US Political Data Collection System repository on GitHub",
  },
  {
    id: "cbs",
    title: "CBS Intelligence",
    subtitle: "Regulatory Analytics from the Ground Up",
    org: "Attorney-General's Department SA",
    period: "Jan 2025 – Mar 2026",
    tag: "Analytics",
    domain: "Government",
    status: "Completed",
    // current: true,
    stack: [
      "Power BI",
      "Python",
      "GIS/ArcGIS",
      "Time series",
      "Regression",
      "SQL",
      "DAX",
      "Statistical Analysis",
      "DataSA",
      "ABS API",
    ],
    summary:
      "Built the first intelligence analytics capability within the CBS Prevention Team — integrating ABS, SA Health, ACCC, and DataSA data into unified dashboards and GIS maps used by the Minister's Office.",
    impact: "Minister's Office reporting · SOPs institutionalised",
  },
  {
    id: "moodq",
    title: "Moodist",
    subtitle: "Mental Health Mobile Application",
    org: "University of Melbourne — Psychiatry",
    period: "Aug 2024 – Feb 2026",
    tag: "Mobile Dev",
    domain: "Research",
    status: "Handed to production team",
    stack: ["Expo", "React Native", "Flask", "Python", "AWS RDS", "LightSail", "CI/CD"],
    summary:
      "A clinician-facing and patient-facing mental health app for the University of Melbourne's Department of Psychiatry, built as sole developer. Rebuilt it from Uniapp to Expo React Native with a clinician dashboard on a Flask backend, kept hosting under $500 a month by running each service in its own Docker container on AWS LightSail, and kept it GDPR-aligned before handing it to a professional team for production.",
    impact: "Sole developer · Hosting under $500/month · Cross-platform iOS + Android",
    caseStudy: "/projects/moodist",
  },
  {
    id: "wehi-flow",
    title: "Genomics Metadata Multiplexing",
    subtitle: "Sample-sheet tooling for plate-based single-cell sequencing",
    org: "WEHI",
    period: "Feb 2024 – Jul 2024",
    tag: "Research Software",
    domain: ["Biotech", "Research"],
    status: "Completed",
    stack: [
      "R",
      "Shiny",
      "Python",
      "reticulate",
      "pandas",
      "fcsparser",
      "Bash",
      "Git",
      "Milton HPC (built to run on)",
    ],
    summary:
      "Worked on Genomics Metadata Multiplexing (GMM), an R Shiny tool that builds CEL-Seq2 sample sheets for plate-based single-cell sequencing. It merges flow-cytometry sort metadata from FACS index-sort files with the plate layout and primer indexes, so nobody has to stitch them together by hand. Wrote the Shiny side of the app, added test inputs with expected outputs, and contributed a column clean-up step to WEHIGenomicsRnD/celseq-sample-sheet-generator.",
    impact:
      "One sample sheet instead of a hand merge · Contribution merged into celseq-sample-sheet-generator",
    caseStudy: "/projects/wehi-genomics",
  },
  {
    id: "factcheck",
    title: "Climate Fact-Checker",
    subtitle: "Automated Fact-Checking for Climate Claims",
    org: "University of Melbourne",
    period: "Apr 2024 – May 2024",
    tag: "NLP / ML",
    domain: "Climate Research",
    status: "Completed",
    stack: [
      "Python",
      "TF-IDF",
      "Transformers",
      "NLP",
      "Virtual Environment",
      "BERT",
      "Hugging Face",
      "PyTorch",
      "spaCy",
      "Scikit-learn",
    ],
    summary:
      "Designed a two-stage automated fact-checking system for climate change claims — TF-IDF evidence retrieval followed by Transformer-based classification (SUPPORTS / REFUTES / NOT ENOUGH INFO / DISPUTED), outperforming LSTM baselines.",
    impact: "Transformer model outperformed LSTM · Scalable misinformation detection pipeline",
    link: "https://github.com/rNLKJA",
    linkLabel: "View Climate Fact-Checker on GitHub profile",
  },
  {
    id: "hex",
    title: "HEX",
    subtitle: "Digital Content Library Builder",
    org: "HEX",
    period: "Nov 2023 – Jun 2024",
    tag: "EdTech",
    domain: "Startup",
    stack: [
      "Content Design",
      "EdTech",
      "Market Research",
      "LLMs",
      "Instructional Design",
      "Curriculum Development",
      "Notion",
      "Interactive Content",
    ],
    summary:
      "Built and refined interactive digital educational content aimed at bridging the gap between education and professional success. Conducted market research on leveraging advanced technologies to improve course engagement and learner outcomes for students across Australia and beyond.",
    impact:
      "80+ students supported · Improved course engagement through technology-driven content innovation",
    link: "https://www.startwithhex.com/",
    linkLabel: "Visit HEX company homepage",
    linkText: "Visit HEX homepage ↗",
  },
  {
    id: "selfdriving-db",
    title: "Self-Driving Databases",
    subtitle: "Workload-Driven Optimisation & Index Selection",
    org: "University of Melbourne",
    period: "Jun 2023 – Jul 2023",
    tag: "Research",
    domain: "AI / ML",
    status: "Completed",
    stack: [
      "Database systems",
      "ML optimisation",
      "Query planning",
      "PostgreSQL",
      "B-tree Indexing",
      "Cost Models",
      "Query Optimisation",
      "Literature Review",
    ],
    summary:
      "Research project exploring AI/ML techniques for autonomous database management — covering workload-driven optimisation and automatic index selection to reduce DBA overhead and improve query performance.",
    impact: "Literature review · Autonomous DB optimisation frameworks",
    link: "https://github.com/rNLKJA",
    linkLabel: "View Self-Driving Databases research on GitHub profile",
  },
  {
    id: "social-cloud",
    title: "Social Media Analytics",
    subtitle: "Australia on the Cloud",
    org: "University of Melbourne",
    period: "Apr 2023 – Jun 2023",
    tag: "Cloud / Analytics",
    domain: "Cloud / HPC",
    status: "Completed",
    stack: [
      "Python",
      "Twitter API",
      "Mastodon API",
      "CouchDB",
      "AWS",
      "SUDO",
      "Pandas",
      "Folium",
      "Matplotlib",
      "Spatial Analysis",
      "REST APIs",
    ],
    summary:
      "Harvested and analysed Twitter and Mastodon data alongside ABS SUDO spatial data to produce a Social Sense Dashboard illuminating Australian sentiment, social trends, and regional behavioural patterns.",
    impact: "Cross-platform social analytics · Spatial + social data fusion",
    link: "https://github.com/rNLKJA/Australia-Social-Media-Analytics-on-the-Cloud",
    linkLabel: "View Australia Social Media Analytics repository on GitHub",
  },
  {
    id: "twitter-hpc",
    title: "Twitter HPC Analysis",
    subtitle: "Big Data on SPARTAN",
    org: "University of Melbourne",
    period: "Mar 2023 – Apr 2023",
    tag: "HPC / Big Data",
    domain: "Cloud / HPC",
    status: "Completed",
    stack: ["Python", "MPI", "SPARTAN HPC", "Parallel computing", "Slurm"],
    summary:
      "Processed a large-scale Twitter dataset on the University of Melbourne's SPARTAN HPC cluster using MPI and Python, identifying tweet distribution across Australian cities and top contributors.",
    impact: "HPC parallel processing · City-level tweet distribution insights",
    link: "https://github.com/rNLKJA/Twitter-Data-Analysis-with-HPC",
    linkLabel: "View Twitter HPC Analysis repository on GitHub",
  },
  {
    id: "climate",
    title: "ENSO Climate Risk",
    subtitle: "Food Security & Conflict Forecasting",
    org: "CSIRO × University of Melbourne",
    period: "Feb 2023 – Nov 2023",
    tag: "Data Science",
    domain: "Climate Research",
    status: "Completed",
    stack: [
      "Python",
      "AR time series",
      "Rolling window",
      "Statistical modelling",
      "Research Software Engineering",
      "Jupyter Notebook",
    ],
    summary:
      "Built AutoRegressive time series models with rolling window forecasting to quantify how El Niño-Southern Oscillation patterns amplify commodity price volatility and food security-induced conflict risk.",
    impact: "Climate → conflict risk insights · 10-month CSIRO research engagement",
  },
  {
    id: "cachex",
    title: "Cachex AI",
    subtitle: "Game-Playing AI Agent",
    org: "University of Melbourne",
    period: "Apr 2022 – Jun 2022",
    tag: "AI / Algorithms",
    domain: "AI / ML",
    status: "Completed",
    stack: [
      "Python",
      "A* pathfinding",
      "Heuristic search",
      "Game theory",
      "Game-playing agents",
      "Minimax",
      "Alpha-beta pruning",
      "Graph search",
    ],
    summary:
      "Implemented AI agents for Cachex — a two-player connection game — covering heuristic A* search for the exploration phase and a competitive game agent using strategic anticipation and sabotage logic.",
    impact: "A* pathfinding · Competitive AI agent · Game theory application",
    link: "https://github.com/rNLKJA/Cachex-AI",
    linkLabel: "View Cachex AI repository on GitHub",
  },
  {
    id: "hplc",
    title: "HPLC Pipeline",
    subtitle: "Medical Research Automation",
    org: "CSL (CSL Behring)",
    period: "Feb 2022 – Jun 2022",
    tag: "Data Science",
    domain: "Biotech",
    status: "Delivered",
    stack: [
      "Python",
      "Scikit-learn",
      "T-SNE",
      "DBSCAN",
      "UMAP",
      "Machine Learning",
      "Research Software Engineering",
      "Jupyter Notebook",
    ],
    summary:
      "Built a Python automation script to streamline HPLC experiment result processing, and applied unsupervised clustering methods to uncover hidden patterns in complex medical research datasets.",
    impact: "Reduced HPLC processing time · Improved data quality confidence",
  },
  {
    id: "pcrm",
    title: "PCRM",
    subtitle: "Personal Customer Relationship Management",
    org: "University of Melbourne",
    period: "Aug 2021 – Nov 2021",
    tag: "Full Stack",
    domain: "Research",
    status: "Completed",
    stack: [
      "Node.js",
      "React.js",
      "Express.js",
      "MongoDB",
      "HTML/CSS",
      "REST API",
      "JWT Auth",
      "Mongoose",
      "Agile",
    ],
    summary:
      "Collaborative full-stack CRM system built as the COMP30022 IT Project — managing customer interactions and data with a responsive React frontend, Express REST API, and MongoDB backend.",
    impact: "Full-stack delivery · Team project · Production-grade architecture",
    link: "https://github.com/rNLKJA/Personal-Customer-Relation-Management-PCRM",
    linkLabel: "View PCRM repository on GitHub",
  },
  {
    id: "nyc-taxi",
    title: "NYC Taxi Analysis",
    subtitle: "Quantitative Analysis with Spark",
    org: "University of Melbourne",
    period: "Jul 2021 – Aug 2021",
    tag: "Data Science",
    domain: "Research",
    status: "Completed",
    stack: [
      "Python",
      "Apache Spark",
      "Machine Learning",
      "Clustering",
      "Pandas",
      "PySpark",
      "Research Software Engineering",
      "Jupyter Notebook",
    ],
    summary:
      "Analysed 2014–2017 New York City Yellow Taxi data using Apache Spark for big data processing, applying linear modelling to predict trip costs and clustering to identify traffic hotspots.",
    impact: "Big data Spark pipeline · Traffic hotspot clustering · Trip cost modelling",
  },
  {
    id: "portfolio",
    title: "rin.contact",
    subtitle: "Personal Portfolio — v5",
    org: "Personal Project",
    period: "2020 – Present",
    tag: "Web Dev",
    domain: "Personal",
    status: "v5 in development",
    stack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Vercel",
      "JavaScript",
      "SEO",
      "Schema.org",
      "JSON-LD",
      "CSS Animations",
      "GitHub Actions",
    ],
    summary:
      "Five major iterations of a personal website — currently rebuilt in v5 with a Nothing OS-inspired minimal design language. A living record of technical and professional development since 2020.",
    impact: "5 major versions · rin.contact · Open source",
    link: "https://github.com/rNLKJA",
    linkLabel: "View rin.contact portfolio on GitHub",
    current: true,
  },
  {
    // Twelve Forage job simulations grouped into one low-priority card, kept last.
    // The repos are private and there is no write-up page, so the card has no link.
    id: "virtual-internships",
    title: "Virtual internships (Forage)",
    subtitle: "Twelve Company-Designed Job Simulations",
    org: "Forage · KPMG, BCG, British Airways, PwC and others",
    period: "Oct 2022 – Aug 2023",
    tag: "Data Science",
    domain: "Personal",
    status: "Completed",
    stack: [
      "Python",
      "pandas",
      "scikit-learn",
      "SHAP",
      "SQL",
      "R",
      "Tableau",
      "Power BI",
      "Excel",
      "PowerPoint",
    ],
    summary:
      "I completed twelve self-paced job simulations on Forage, each designed by the company that set the brief. The companies were KPMG, BCG, British Airways, Quantium, Tata, Cognizant, GE Aviation, Accenture, Red Bull, PwC (two) and Standard Bank. The work covered customer analytics, churn and booking models, dashboards and data joins.",
    impact: "12 job simulations · Oct 2022 – Aug 2023 · analytics, ML and visualisation",
  },
];
